#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
title: Home Automation and Energy Management Blog
description: My Blog on energy and other Home Automation topics!
comments:
  provider: giscuss
  
giscus:
  repo:                "LazyRen/LazyRen.github.io"
  repo-id:             "R_kgDOKFCyUw"
  category:            "Comments"
  category-id:         "DIC_kwDOKFCyU84CYgNv"
  mapping:             "url"
  reaction-enabled:    "1"
  theme:               "dark_dimmed"
  crossorigin:         "anonymous"
paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-feed
