# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "github-pages-health-check"
gem "github-pages"
gem "html-pipeline"
gem "jekyll-avatar"
gem "jekyll-coffeescript"
gem "jekyll-commonmark-ghpages"
gem "jekyll-default-layout"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-include-cache"
gem "jekyll-mentions"
gem "jekyll-optional-front-matter"
gem "jekyll-readme-index"
gem "jekyll-redirect-from"
gem "jekyll-relative-links"
gem "jekyll-remote-theme"
gem "jekyll-sass-converter"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-swiss"
gem "jekyll-titles-from-headings"
gem "jemoji"
gem "kramdown-parser-gfm"
gem "kramdown"
gem "liquid"
gem "minima"
gem "nokogiri"
gem "rouge"
gem "ruby"
gem "safe_yaml"
gem "sass"
#gem "bulma-clean-theme"
gem "webrick"
